services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    # ports:
    #   - "2181:2181"

  kafka-server:
    image: bitnami/kafka:3.5
    container_name: kafka-server
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT



  topic-creator:
    image: apache/kafka:3.7.2
    depends_on:
      - kafka-server
    entrypoint: [ "sh", "-c", "
      while ! nc -z kafka-server 9092; do sleep 1; done;
      sleep 5;
      echo 'Creating topics...';
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-server:9092 --create --if-not-exists --topic pizza-orders;
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-server:9092 --create --if-not-exists --topic pizza-live-stats;
      echo 'Topics created successfully.';
    "]

  datagen:
    build:
      context: datagen
    depends_on:
      - kafka-server
      - topic-creator
    volumes:
      - filesink:/opt/bitnami/kafka/filesink

  spark:
    build:
      context: spark
    depends_on:
      - kafka-server
      - topic-creator

volumes:
  filesink: