version: '2'

services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DEFAULT_BUCKETS=pizza-orders,spark-batch-output
    volumes:
      - 'minio_data:/bitnami/minio/data'
    networks:
      - lambda-example
   
volumes:
  minio_data:
    driver: local

networks:
  lambda-example:
    external: false
    name: lambda-example