services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - lambda-example

  kafka-server:
    image: bitnami/kafka:3.5
    container_name: kafka-server
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    networks:
      - lambda-example

  topic-creator:
    image: bitnami/kafka:3.5
    depends_on:
      - kafka-server
    entrypoint: [ "sh", "-c", "
      echo 'Creating topics...';
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-server:9092 --create --if-not-exists --topic pizza-orders;
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-server:9092 --create --if-not-exists --topic pizza-live-stats;
      echo 'Topics created successfully.';
    "]
    networks:
      - lambda-example

  datagen-source:
    build:
      context: datagen/source
    depends_on:
      - kafka-server
      - topic-creator
    networks:
      - lambda-example

  datagen-sink:
    build:
      context: datagen/sink
    depends_on:
      - kafka-server
      - topic-creator
    volumes:
      - filesink:/opt/bitnami/kafka/filesink
    networks:
      - lambda-example

volumes:
  filesink:
    external: false
    name: filesink

networks:
  lambda-example:
    external: false
    name: lambda-example